### PR TITLE
Added instance ip copy button

### PR DESCRIPTION
**Pull request by neeleshbisht99**
Fixes [#1777](https://github.com/oxidecomputer/console/issues/1775)

### CODE REVIEW

**Comment by benjaminleonard** [comment]
Thanks for the PR Neelesh – but I'd like to hold off on this until we figure out exactly how we want to handle inline copying of table values. It's a pattern we'll likely re-use in a few places so I want to approach this holistically. Or if indeed a copy button is the right solution, as this is an IP, we might want to just wrap it in an anchor tag and the use can simply right click -> copy link address within their browser.

**Comment by david-crespo** [comment]
Thanks Neelesh. We're going to close this for now while we figure it out.

**Comment by neeleshbisht99** [comment]
Hi @david-crespo @benjaminleonard , thanks for the heads up. 
Can you point me to another issue where I can be helpful?

**Comment by david-crespo** [comment]
Unfortunately, not really. As we say in [CONTRIBUTING.md](https://github.com/oxidecomputer/console/blob/main/CONTRIBUTING.md), we're a very small team and it's hard enough to coordinate and prioritize work amongst ourselves even with the full context we have from working here. Issues labeled [`bug`](https://github.com/oxidecomputer/console/issues?q=is%3Aissue+is%3Aopen+label%3Abug) are an ok starting point, though again, I'd caution you that something like the above could easily happen with those.

**Pull request closed without merging**
