### PR TITLE
Fix missing key on intersperse map

### PR DESCRIPTION
**Pull request by benjaminleonard**
Fixes error on `InstancesPage` with missing key on map

### CODE REVIEW

**Comment by david-crespo** [comment]
I don’t think this works because the commas all have the same key

**Comment by benjaminleonard** [comment]
How about this one?

**Comment by david-crespo** [comment]
That will definitely shut React up, at least. Let me give it one more try before we merge this.

**Comment by david-crespo** [comment]
Covered in #1912

**Pull request closed without merging**
