### PR TITLE
More helpful empty projects table text

### PR DESCRIPTION
**Pull request by david-crespo**
Thought of this while listening to a podcast about UI design. The system works!

Screenshot 2024-09-04 at 4 09 52 PM

### CODE REVIEW

**Comment by benjaminleonard** [comment]
Great!

We usually omit the full stop if there's just one sentence right?

**Comment by david-crespo** [comment]
Usually, though mentally I have a sort of line where if it gets too long it starts to feel like it needs a period. Generally the rule should be: if it's a sentence, give it a period. We've been leaving it out because most of these are short, but tbh the existing ones look a bit silly too.

image

**Comment by benjaminleonard** [comment]
What can I say, I'm a minimalist

**Comment by david-crespo** [comment]
Fine, I can deal.

image

**Comment by david-crespo** [comment]
Fine, I can deal.

Screenshot 2024-09-04 at 4 48 58 PM

**Pull request merged**
